o:
  source: /mnt/recorder/data/O
  destination: /mnt/o_reports

z:
  source: /mnt/recorder/data/Z
  destination: /mnt/z_reports

r:
  source: /mnt/recorder/data/R
  destination: /mnt/r_reports

x:
  source: /mnt/recorder/data/X

archive: archive
